FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY subserver.py .
COPY templates ./templates

RUN ls -l /app/templates

CMD ["python", "subserver.py"]